# Generated by Django 4.0.4 on 2022-05-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0007_alter_month_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
